### ISSUE TITLE
MF: resources & scss

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#14]
Currently the `mf-builder` requires the Angular component to have styles inlined within the component and we don’t support the `styleUrls`

- Extends existing webpack build to also understand `styleUrls`
- Support for assets in the same how we use it inside angular.json
- Bundle project the same way as angular, where we have a few JS files that includes vendor code, application code. Right now we have java scripts for each component

**Comment by valorkin** [comment]
@fkolar 
- `Support for assets in the same how we use it inside angular.json` 
  assets is handled already, but each micro app independently. I would say `as designed`
- `Bundle project the same way as angular, where we have a few JS files that includes vendor code, application code. Right now we have java scripts for each component`
  this should a separate issue, cc @skocharian
