### ISSUE TITLE
MF:Schematics to configure webpack

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#15]
Once **MF: Resources & scss**  is done we need to automate this with set of  schematics. 

- Create schematics that can generate Webpack configuration based on the angular JSON
-- New project:  @fundamental-ngx/app-shell:ng-add		
-- Existing project: @fundamental-ngx/app-shell:generate schematics 		
- Reorg- existing angular structure to match our ng-mf-submodules

**Comment by valorkin** [comment]
Issue moved to [valorkin/module-federation #34](https://github.com/valorkin/module-federation/issues/34) via [**ZenHub**](https://www.zenhub.com/)
