### ISSUE TITLE
MF: iFrame Support

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#18]
Besides supporting Angular only solution as micro-front-end component we also need to support some other legacy systems using iFrames (Which are probably based on Java Servlets). To goal is to wrap iFrame complexity into web component to encapsulate internal iFrame details and manage all the URL assembly as well as security related topics.
- Develop web-component which will contains iFrame.
- This needs to manage all the styles for double scrollbars and overflows.
- It will also use window `post messages & listeners` to communicate with in the iFrame.
-- Here we need to introduce some common protocol. that application teams and iFrame source application can use to exchange informations
- Security: TBD - need to find out SAP restrictions such as passing token in urls
- Test if this web component can subscribe to existing message bus to communicate with the shell-bar
-- Most likely shell-bar will set the Angular Service object to the window object.
-

**Comment by valorkin** [comment]
Developing web component for Angular app shell doesn't make sense. It will be an angular component
