### ISSUE TITLE
Error Management

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#19]
Create a communication channel for the error management and create an API so the application can post errors that can be aggregated in one place on the app-shell level. 

We should identify different sets of errors (system error, application errors, network errors, different severity levels?)

Provide ErrorHandler implementation that we can attach to regular NG Handler, so we will leave it up to the application how to handle errors - more like angular way.

**Comment by valorkin** [comment]
1. Provide ErrorHandler on top of message bus
2. Provide a way to send Error to message bus
