### ISSUE TITLE
Schematics to structure project

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#21]
Create _generate_ schematics that will preconfigure webpack config. But this should have a dependency on current mf-builder work, if we get more closer to the ng commands - so this one probably has a lower priority than the other tasks. Low priority

**Comment by fkolar** [comment]
@skocharian let;s move this to M3, as this will have dependency to a task where we integrate CLI build with ngx-build-plus

**Comment by valorkin** [comment]
Issue moved to [valorkin/module-federation #33](https://github.com/valorkin/module-federation/issues/33) via [**ZenHub**](https://www.zenhub.com/)
