### ISSUE TITLE
Plugin Permissions

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#22]
Create or extends configuration to keep it apart from the way we have (as part of the plugin), so plugin permission can be loaded by one-bx-application. It will list different permission defined by one-bx-developer or microservice, such as:

•	Permission to listen to theme change
•	Can talk to AppShell 
•	Can talk to other apps (app:event)
•	Can propagate errors to app:shell (for the application - plugins)
•	Can create custom Topics

Depending on what permission is enabled we need to update existing code inside PluginManager to add or remove certain topics from the list or enable or disable creating certain topics. or Drop communication (Publishers, Subscribers)

We can maybe just extend our plugins.json for new property permissions: [xxx, aaa, ccc] and this can be quick.

**Comment by valorkin** [comment]
Issue moved to [valorkin/module-federation #31](https://github.com/valorkin/module-federation/issues/31) via [**ZenHub**](https://www.zenhub.com/)

**Comment by valorkin** [comment]
Issue moved to [valorkin/module-federation #32](https://github.com/valorkin/module-federation/issues/32) via [**ZenHub**](https://www.zenhub.com/)
