### ISSUE TITLE
Plugin configuration

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#26]
Finalize configuration structure, add, remove properties as needed, including _framework=legacy, angular, vue, react, wc, ui5_, permission properties. 
This relates to tasks above. New property for permission, framework - maybe instead of developing something here, is this more a checkpoint.

**Comment by valorkin** [comment]
angular, iframe, webpack - we can do right now

legacy, vue, react, ui5 - later
permission - later
