### ISSUE TITLE
MF: Bundling 

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#27]
The current build process _(mf-builder)_ when it compiles our projects it outputs individual files for each component with. we should have a similar build process as angular where it packages everything into bundles. 

This task should be the last one.

**Comment by valorkin** [comment]
@fkolar @skocharian need more details about this one

**Comment by fkolar** [comment]
I think you have addressed thsi in the other issue 

Bundle project the same way as angular, where we have a few JS files that includes vendor code, application code. Right now we have java scripts for each component
this should a separate issue, cc @skocharian

#14

**Comment by fkolar** [comment]
But this is not for this sprint..

**Comment by fkolar** [comment]
Changing to sprint 3, as we need to investigate more how to integrate MF CLI

**Comment by valorkin** [comment]
@fkolar we did all we can with a new builder, now only cli improvements will help
