### ISSUE TITLE
Gitbook, Guidelines

### ISSUE THREAD

**Issue by skocharian** [valorkin/ng-mf-submodules#28]
update Gitbook with clear guidelines how to get:

 - How to install our environment to new and existing projects
 - Describe Project structure and where to find what
 - Create new page Tutorial By Example, where we almost each sample we will have and describe how to :
   - Expose Angular|WebComponnet|iFrame service to be consumed by remote host
   - How to use Plugin Launcher and how we work with Plugin Configuration
   - MessageBus and list existing topcis
   - Describe Error Managements
   - How to comunicate with iFrames using RPC
   - Routing
   - State Management. 
- How to setup development environment and how to test MF apps inside emulated appshell

**Comment by fkolar** [comment]
Should we get technical writter for this? Now we have 2 of you full time and me working on this from like 30%.

**Comment by valorkin** [comment]
Issue moved to [valorkin/module-federation #28](https://github.com/valorkin/module-federation/issues/28) via [**ZenHub**](https://www.zenhub.com/)
