### ISSUE TITLE
mf-builder does not report invalid html

### ISSUE THREAD

**Issue by fkolar** [valorkin/ng-mf-submodules#35]
When you do `ng build`  and there is some component with non-existing bindings angular compiler tells us this. 

e.g. 

```
<fds-plugin-laucher id="nx.yourFavorite"></fds-plugin-laucher>
```
`id` does not existing anymore as I renamed this to `name`

let's track these issues.

**Comment by valorkin** [comment]
@fkolar it does with new builder
