### ISSUE TITLE
Part 2 - Communication strategies

### ISSUE THREAD

**Issue by ZhmenZH** [valorkin/ng-mf-submodules#41]
The second iteration on our topics and subscribers, we need to provide a more seamless API to use. We will stick with the listeners we have; we just need to update API that we are putting into PluginContext. 

AppShell have AppShellProvider, here he it needs to be able to access both publishers and subscribers, easy the method.

- Instead of pre-creating publishers create all this lazily, the same goes for subscribers

Plugins - Listeners are provided as part of the PluginConfiguration, Publishers are provided inside PluginContext to better control what is exposed and how. Should we have all in one place? And remove the concept of Plugin configuration? When we are not going to support extension points, actions etc..?

Update necessary example code 

_There is also a question, when we use module federation do we need MessageBus? Some messaging is definitely needed but these plugins should feel more native (See Plugin Bindings support)_

**Comment by valorkin** [comment]
Sample: ThemeProvider -> ThemeConsumer, scope access regulated via plugins.json registration

**Comment by fkolar** [comment]
Update API, so I dont pre-create all the publishers and make all more lazily.
