### ISSUE TITLE
Part 2 - Plugin Bindings

### ISSUE THREAD

**Issue by ZhmenZH** [valorkin/ng-mf-submodules#43]
Module federation way is more to use components bindings just like you would use it in Angular or any other framework and less using message-bus. This applies regardless if we are dealing with Angular based plugin, Web Component or any other framework.

We should enable _PluginLauncher_ with Bindings support so application can pass and read data in order to communicate more natively with the target application 
Ideally we want something like:

`<fds-plugin-launcher name="Basket" [bindings]="MapKeyValue" events="MapWithEvents"> </fds-plugin-launcher>`

`<fds-plugin-launcher name="Basket" sectionTitle="This is basket details" (click)="OnAddToCard($evemt)"></fds-plugin-launcher>`

We should enable it to read inputs & outputs from the instantiated component or from created web component element and connect this with attributes on the host `<fds-plugin-launcher>` component

**Comment by valorkin** [comment]
via ngAst or via angular language service
element schema can be generated via custom angular builder, or meta-ui

**Comment by fkolar** [comment]
The same like the other tasks M3
