### ISSUE TITLE
Part 2 - Remote module loading error

### ISSUE THREAD

**Issue by ZhmenZH** [valorkin/ng-mf-submodules#44]
If a host can’t import a module when it tries we return a blank module or not allowed callback and registration

**Comment by valorkin** [comment]
each launcher will have it's own onerror handler, if downloading of module\iframe\webcomponent downloading fails
3 retries by default, and globally configurable 
and generic error handler on top of it

**Comment by fkolar** [comment]
@skocharian Let's move this one to M3
