### ISSUE TITLE
Module federation routing

### ISSUE THREAD

**Issue by ZhmenZH** [valorkin/ng-mf-submodules#49]
In item-page.component add the ability to lazy load children of subroutes.

This task will execute diferent scenarios to investigate:
 - Add `RouteModule.forChild` directly to `AppModule` of (item-page.component)
 - Use function `loadRemoteModule` directly with` loadChildren`
 - Work directly with `Router` and `resetConfig` with routes coming from remote module

**Comment by ZhmenZH** [comment]
To add the ability to lazy load children of subroutes.

**Comment by valorkin** [comment]
@fkolar this is merged, closing
